export const OFFICE_SUITE_SKILL_NAME = 'office-suite';

export function buildOfficeModeProtocol(): string {
  return [
    '## Office 模式协议',
    '',
    '当前会话开启了 Office 模式。处理 PPTX/DOCX/XLSX/PDF/HTML/Slidev/Canvas/文件解析时，必须把办公产物当作可多轮编辑和验收的工程交付，而不是一次性文本输出。',
    '',
    '### 工作流闭环',
    '',
    '- 首选闭环：先 inspect/parse，拿到页码、element_id、坐标、图片关系、文本层和页面尺寸，再 generate/edit，最后 office_ops(action="validate") 或打开矩阵验收。',
    '- 允许 Python/LibreOffice/OOXML 作为一等路线：复杂排版、图片处理、批量 OOXML 修改、转换验收、截图/缩略图生成，可以用 office_ops(action="runtime")、python_exec 或 shell 调脚本完成；根据任务选择最合适的运行时。',
    '- LLM 很少一次成稿。必须支持 inspect -> edit -> validate -> review 的循环，按页、按元素、按精确坐标和文本锚点改稿。',
    '- 深水区优先用 office_ops(action="runtime") 兜底：unpack_ooxml/pack_ooxml/strict_validate_ooxml/pptx_thumbnail/xlsx_recalc/pdf_to_images 是内置 Office runtime，不需要用户额外安装 skill。',
    '- 如果用户没有指定 HTML 还是 PPTX/DOCX/PDF，按交付物语义处理：演示/幻灯片默认优先原生可编辑 PPTX；长文档优先询问 DOCX/PDF/HTML。明确原生 Office 时必须优先生成原生可编辑文件。',
    '- PPTX 默认路线：用户要 PPT/PPTX/PowerPoint/客户可编辑交付时使用 generate_pptx（底层 pptxgenjs 原生形状）；后续改稿用 edit_pptx。不要用 HTML/Slidev 静默替代。',
    '- HTML 演示路线：只有用户明确要网页演示、交互动画、HTML 预览，或要同一 HTML 高保真导出 PDF/PNG/PPTX 时才用 generate_html_presentation / generate_html_document；其中 HTML 导出的 PPTX 是逐页 PNG 贴图，文字不可编辑，交付前必须说明。',
    '- DOCX 默认路线：明确要 Word/DOCX/可编辑文档时使用 generate_docx（底层 docx），后续改稿用 edit_docx。PDF 默认路线：结构化普通 PDF 用 generate_pdf（pdfkit），复杂视觉/CSS/分页高保真 PDF 用 generate_html_document 导出 PDF（Chromium）。',
    '',
    '### 设计哲学（凌霄审美标准）',
    '',
    'Office 产物不是信息容器，是设计交付物。以下原则是审美门槛，不是建议：',
    '',
    '- **克制即高级**：每页一个核心信息，一个主结构，足够视觉证据支撑论点。拒绝信息堆砌。一页超过 6 条要点即过载。',
    '- **留白是设计**：负空间和内容同样重要。页面呼吸感优先于信息密度。 margins ≥ 48px，元素间距 ≥ 24px。',
    '- **层级即节奏**：标题/正文/辅助/装饰四级分明，字号对比要大胆（标题 ≥ 正文 1.5 倍），不要全页一个节奏。',
    '- **色彩即语言**：一个主色 + 一个强调色 + 中性灰阶，总计不超过 3 个有色。禁止彩虹配色、禁止默认蓝白、禁止高饱和堆叠。',
    '- **字体即气质**：标题用衬线/展示体传达正式感，正文用无衬线保证可读性。CJK 优先思源宋体/苹方/微软雅黑。禁止全页 Arial 或单一字体。',
    '- **栅格即骨架**：稳定的内容栅格（12 列或黄金分割），页眉页脚页码统一。不要随机间距和随意对齐。',
    '- **图片即证据**：图片不是装饰而是信息载体。保持比例，选择 contain/cover，避开标题和证据区，必要时加图注/alt text/attribution，并通过 office_ops(action="validate") 检查媒体 relationship。',
    '',
    '### 禁止清单（审美红线）',
    '',
    '以下行为在任何 Office 产物中一律禁止，违反任一条即不交付：',
    '',
    '- 禁止 emoji 作为内容元素或装饰（⚠️ 📊 🚀 💡 ✅ ❌ 等全部禁止）。用排版层级、色彩对比和几何元素替代。',
    '- 禁止通用 AI 排版（居中标题 + 三列要点 + 蓝色渐变背景的"ChatGPT 风"）。',
    '- 禁止默认蓝白配色（#0066CC + #FFFFFF 的 PowerPoint 默认风）。',
    '- 禁止纯文字幻灯片（没有视觉结构、没有图表、没有图片支撑的"bullet wall"）。',
    '- 禁止随机间距和对齐（每个元素的位置必须有栅格依据）。',
    '- 禁止高饱和彩虹配色（超过 3 个高饱和色同时出现）。',
    '- 禁止全页统一字体（标题和正文必须有字体对比）。',
    '- 禁止"安全企业风"作为唯一选项（灰蓝白三件套不是万能模板）。',
    '',
    '### 风格覆盖要求',
    '',
    'Office 产物不应只有一种风格。根据内容性质选择匹配的设计语言，不要默认用同一套模板：',
    '',
    '- **商务汇报**（lingxiao_board）：克制深色/白底信息密度，稳定页脚，适合董事会/经营会。',
    '- **企业报告**（enterprise_report）：低饱和蓝灰体系，清晰页眉页脚，适合方案书/汇报材料。',
    '- **产品策略**（product_strategy）：墨色正文配低饱和靛蓝和琥珀点缀，适合策略叙事。',
    '- **墨韵极简**（ink_wash）：松烟暖炭为骨、宣纸暖白为肉、剑金为锋的极简水墨，适合内部分享/文化叙事。',
    '- **朱砂典藏**（vermilion）：朱砂印为魂、墨底金线，适合年报/总结/典藏气场。',
    '- **青锋科技**（cyan_blade）：青锋冷光暗色底，适合产品/技术/数据主题。',
    '- **金箔商务**（gold_leaf）：暖纸金箔，适合提案/商业计划/咨询气场。',
    '- **编辑杂志**（editorial）：大标题 + 多栏排版 + 引文块 + 图片叙事，适合深度报告/白皮书/洞察文章。',
    '- **暗色高级**（dark_luxury）：墨黑底 + 金/银强调 + 大量留白，适合品牌/战略/发布会。',
    '- **宣纸纯净**（papyrus）：最低存在感，打印/长文档/学术/合同。',
    '',
    '### 模板系统',
    '',
    '原生 PPTX/DOCX 使用 OfficeTemplateRegistry 预设（10 套），HTML 产物使用 themes.ts 主题（8 套），两套系统通过 htmlThemeId 映射对齐。选择模板时根据内容性质匹配风格，不要默认用同一套。可用 design_asset 查询主题参考站做审美校准。',
    '',
    '### PPTX 商务交付结构',
    '',
    '先设计母版/主题/版式节奏，再落页：封面、章节页、证据卡片、矩阵/时间线/路径图、行动页要有稳定栅格、页眉页脚、页码和品牌语气。每张幻灯片需要一条核心信息、一个主结构和足够的视觉证据使其可扫描。',
    '',
    '### 质量门槛',
    '',
    '产物完成前必须通过：',
    '- 输出文件存在且格式正确。',
    '- 期望文本存在，页/幻灯片/工作表数匹配意图。',
    '- 图片和媒体关系完整。',
    '- 生成的 OOXML 可读。',
    '- comments/revisions/charts/timing/formulas 已验证（如使用）。',
    '- LibreOffice/WPS/Office 打开检查已执行或明确报告为不可用/跳过。',
    '- **审美检查**：对照禁止清单逐条确认，任何一条违反则不交付。',
    '- 审计记录包含 session、agent、tool、args、output path、hash 和 timestamp（如支持）。',
  ].join('\n');
}
