export const OFFICE_SUITE_SKILL_NAME = 'office';

export function buildOfficeModeProtocol(): string {
  return [
    '## Office 模式协议',
    '',
    '当前会话开启了 Office 模式。处理 PPTX / DOCX / XLSX / PDF 等办公产物时，把它当作可验收的设计交付物，不是一次性文本输出。',
    '',
    '### 生成路线：用 shell 跑 Node 脚本直调库',
    '',
    'office 产物不再有固定 schema 的 generate_* 工具。你直接用 `shell` 执行 Node 脚本，require 下列已安装的库自由生成，释放库的完整能力，不受任何字段约束：',
    '',
    '- **PPTX** → `pptxgenjs`：母版/主题/版式、形状、文本框、表格、图表、图片、备注、精确坐标（英寸）。',
    '- **DOCX** → `docx`：段落/标题/样式、表格、分栏、页眉页脚、目录、图片、分页。',
    '- **XLSX** → `exceljs`：多工作表、列宽、公式、条件格式、单元格样式、冻结窗格、图表。',
    '- **PDF** → `pdfkit`：精确排版、字体、矢量图形、图片、多页、书签。',
    '',
    '落地方式（任选其一，按复杂度选择）：',
    '- 简单产物：`shell` 跑 `node -e "..."` 一行式调库。',
    '- 复杂产物：先 `file_create` 写一个临时 `.mjs`（或 `.cjs`）脚本到工作区，再 `shell` 跑 `node 脚本.mjs` 执行，便于多轮迭代和调试。',
    '- 库是 CommonJS 时用 `require()`（`.cjs` 或 `node -e`）；ESM 入口用 `import`（`.mjs`）。pptxgenjs/docx/exceljs/pdfkit 均支持 `const X = require("X")`。',
    '- 注意：`node_repl` 是无 require 的 vm sandbox，不能直调这些库；生成产物必须走 `shell` + node。',
    '',
    '最小骨架示例（PPTX）：',
    '```js',
    '// gen_deck.cjs — node gen_deck.cjs',
    'const PptxGenJS = require("pptxgenjs");',
    'const pptx = new PptxGenJS();',
    'pptx.defineSlideMaster({ title: "MASTER", background: { color: "0E1116" } });',
    'const s = pptx.addSlide({ masterName: "MASTER" });',
    's.addText("核心论点", { x: 0.6, y: 0.5, w: 8.8, h: 1, fontSize: 40, bold: true, color: "F5C451" });',
    's.addText("支撑证据一句话", { x: 0.6, y: 1.7, w: 8.8, h: 0.6, fontSize: 18, color: "C9CDD4" });',
    'pptx.writeFile({ fileName: "deck.pptx" }).then(() => console.log("done"));',
    '```',
    '',
    '### 审美门槛（不是建议，是交付前提）',
    '',
    'Office 产物是设计交付物。生成前先读取 office skill 的完整审美指导，对齐风格库 / 禁止清单 / 留白层级，再动手写脚本：',
    '',
    `- 注入的 \`${OFFICE_SUITE_SKILL_NAME}\` skill 提供 10 套风格库（真实 hex 配色 + 字体 + 适用场景）、设计四原则（克制 / 留白 / 层级 / 色彩）和禁止清单。配色和字体直接取该 skill 的真实值，不要自己编。`,
    '- **克制即高级**：每页一个核心信息、一个主结构、足够视觉证据。一页超过 6 条要点即过载。',
    '- **留白是设计**：margins ≥ 0.5 英寸，元素间距充足，页面呼吸感优先于信息密度。',
    '- **层级即节奏**：标题 / 正文 / 辅助 / 装饰四级分明，标题字号 ≥ 正文 1.5 倍。',
    '- **色彩即语言**：一个主色 + 一个强调色 + 中性灰阶，总计有色不超过 3。禁止默认蓝白、禁止彩虹配色、禁止高饱和堆叠。',
    '- **栅格对齐**：每个元素的位置必须有栅格依据，禁止随机间距和对齐。',
    '- 根据内容性质选匹配风格（商务汇报 / 企业报告 / 产品策略 / 墨韵极简 / 朱砂典藏 / 青锋科技 / 金箔商务 / 编辑杂志 / 暗色高级 / 宣纸纯净），不要默认套同一模板。可用 `design_asset` 查询主题参考站做审美校准。',
    '',
    '### 验收：写完必须转图自检',
    '',
    '产物生成后用 `office_ops(action="runtime")` 做客观验收，这是内置 Office runtime，无需额外安装：',
    '',
    '- `pptx_thumbnail`：PPTX 逐页转图，肉眼核对排版 / 留白 / 配色 / 层级。',
    '- `pdf_to_images`：PDF 逐页转图核对。',
    '- `strict_validate_ooxml`：校验生成的 PPTX/DOCX/XLSX 的 OOXML 是否合法可读。',
    '- `xlsx_recalc`：重算 XLSX 公式，确认计算结果正确。',
    '- 解析 / 复核已有文件用 `parse_file`（支持 PDF/Word/Excel/PowerPoint 等）。',
    '',
    '### 质量门槛 checklist',
    '',
    '产物完成前逐条确认，任何一条不过则不交付：',
    '- 输出文件存在且格式正确（转图 / 解析能打开）。',
    '- 期望文本存在，页 / 幻灯片 / 工作表数匹配意图。',
    '- 图片和媒体关系完整。',
    '- 生成的 OOXML 通过 strict_validate_ooxml。',
    '- 公式 / 图表 / 表格已验证（如使用）。',
    '- **审美检查**：对照 office skill 的禁止清单逐条确认，转图肉眼核对留白 / 层级 / 配色 / 对齐。',
  ].join('\n');
}
